services:
  dbAgenda:
    image: postgres:17
    container_name: dbAgenda
    ports:
      - "5010:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: agenda
    networks:
      - agenda_poli
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "agenda"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  agenda_poli:
    driver: bridge
